### ISSUE TITLE
Dashboard loads twice with extension

### ISSUE THREAD

**Issue by MattVoda** [tableau/extension-data-driven-parameters#29]
Hi,

Loving the extension - I'm using it to populate a list of dates that feed stored procedure params pulling in data for the vizzes the rest of the dashboard. Importantly it defaults to a 'Most Recent' date. When viewing the dashboard in Tableau Server, the page first loads the vizzes with the date that was Most Recent at time of upload (typically a few days out of date), then the extension populates, then the dashboard reloads with the new Most Recent date. This reload/repaint is about 40% of the load time, so I'd really like to try to reduce it.

Can you shed any light on what's happening here?
Perhaps it's standard Tableau caching behavior. If this is the case, then shortening my cache times might help, right?
Perhaps it's an order-of-operations thing? I want the extension to update ASAP and first, so other vizzes immediately have the date they need to get stored proc data. Any tips on how to prioritize the extension and its stored proc? I tried naming the sheet connected to the extension with a prefix of 'aaa' but it doesn't seem to do anything.

Thanks for the great extension!
-Matt

**Comment by KeshiaRose** [comment]
Hi @MattVoda,

This is by design, all extensions load after the dashboard has loaded. This is so we can first get the data that supplies the values to the extension. Unfortunately, there is no way to update the parameter from an extension before rendering the vizzes. 😞 If you have developer resources, one workaround would be to clone and customize the extension so that it sets the parameter or some other dummy filter/parameter to a value that will load no data upon initial load. Then update your date parameter and then flip the dummy filter/parameter so that the data loads based on the correct date value. This would cut down on load times since the first pass would load no data. Hope this helps!

Take care,
Keshia
