### ISSUE TITLE
Parameter visible in desktop but hidden on the server

### ISSUE THREAD

**Issue by saarporat** [tableau/extension-data-driven-parameters#4]
Hi,
This extension is great! it helped us to filter in a dynamic way using Level of details expression (Specifically using the parameter value in FIXED expression). 
Thanks alot!
It worked good for a while but recently the following happened:

- The parameter drop down is visible in Tableau desktop:

![data-driven-parameter-valid-value-in-desktop](https://user-images.githubusercontent.com/13285571/54127366-45a43400-4412-11e9-8155-0f00272b7ca6.png)

- But, it's hidden when looking on the published dashboard. What 
 you do see instead is a grey empty rectangle. See the following screenshot:

![data-driven-parameter-blank-area](https://user-images.githubusercontent.com/13285571/54127536-aaf82500-4412-11e9-8aac-3eb9e02da984.png)

- When open Tableau Server ==>Settings ==> Extensions I get the following error:
"An unexpected error occurred while processing your request. Try again.
undefined" - see screenshot attached
![data-driven-parameter-error](https://user-images.githubusercontent.com/13285571/54126863-3375c600-4411-11e9-93a7-2b92dd55b236.png)

Can you give an advice to handle it?
thanks

**Comment by KeshiaRose** [comment]
Hi @saarporat, 

Would you be able to do the following steps:
1. Restart your server and see if you are still having this issue.
2. If you are still having this issue after restarting, create a [zip of your logs](https://onlinehelp.tableau.com/current/server/en-us/logs_archive.htm) and attach them in a [support case](https://www.tableau.com/support/case). Let me know the number of the support case and my team can take a look at them.

Please know that you may need to upgrade in order to fix this issue. 

Take care,
Keshia

**Comment by saarporat** [comment]
Solved.
Thanks @KeshiaRose
