### ISSUE TITLE
Question: Users need Interactor permission for DDP to work

### ISSUE THREAD

**Issue by MattVoda** [tableau/extension-data-driven-parameters#42]
On our Tableau Server, it seems like the DDP extension does not work for users with only Viewer permission. When promoted to Interactor, the extension works normally.
This is fine. Though I'm curious what minimum components of Interactor permission are needed -- I suspect it's Filter or Web Edit specifically.

Please feel free to close this right away, more a question than issue.

**Comment by KeshiaRose** [comment]
Hi @MattVoda,

All site roles including Viewers are able to use the DDP extension. However, they will need to have the "Download Summary Data" (or the higher level "Download Full Data") permission allowed in order for it to work. Hope this helps! 😃

Take care,
Keshia

**Comment by MattVoda** [comment]
Hey @KeshiaRose ,

Is there an instance where the user will need Download **Full** Data permission instead of Download **Summary** Data?

--Matt

**Comment by KeshiaRose** [comment]
Hey @MattVoda,

Only if the extension has access to underlying data and makes calls to underlying data. Then they will need Download Full Data permission.

Take care,
Keshia

**Comment by mac471** [comment]
Hi Keshia - this is a great dashboard extension.  I just ran into this issue where the extension was updating for me (because I have admin rights) but not for my users (who did not have Download Summary Data rights). I didn't see this post (or use the right search keywords) until after I had narrowed down the problem using a process of elimination.

A suggestion might be to put something on the home page or at this link: [Data Driven Parameters](https://tableau.github.io/extension-data-driven-parameters/#/) to indicate the users of this extension on Server or Online must give users the Download Summary Data access right.  Might save some other people time in the future. Thanks again!
