### ISSUE TITLE
Parameter values not updating automatically

### ISSUE THREAD

**Issue by ekipatez** [tableau/extension-data-driven-parameters#6]
Hi, this is a great extension for Tableau, thanks a lot :)

I have my parameter half way down the dashboard, and one issue I seem to have is the parameter values don't update automatically if the corresponding worksheet is filtered. They will only update and refresh once something is picked. Is there a solution to this at all? I was hoping for it to act in a similar way to a quick filter set to 'only relevant values'

Cheers

**Comment by KeshiaRose** [comment]
Hi @ekipatez, 

The expected behavior is to do exactly as you described when you have the "Filter parameter list based on worksheet selections" option checked. Is this option on? If so, what kind of filter are you using? Could you give me more detail about the dashboard?

Take care,
Keshia

**Comment by ekipatez** [comment]
Hi Keshia,

I have the option turned on. Basically I have an overarching quick filter for the field ‘campaign’ at the top of the dashboard, and then this parameter sits half way down to provide a further filter on the ‘campaign’ field (there’s a reason it needs to be a parameter and not another quick filter, which I won’t go into as it’s not relevant). The values in the parameter need to reflect what is in the quick filter when the quick filter is changed.

What is happening at the moment is:
If a selection is chosen from the quick filter, the parameter still shows all values UNTIL the parameter value is changed – only then does the parameter list refresh and change to reflect the quick filter. So it seems that the parameter list is not automatically refreshing with the quick filter.

I hope this makes sense?

Thanks

**Comment by KeshiaRose** [comment]
Hi @ekipatez,

I'm unable to reproduce your issue. :(  https://bit.ly/2UCFtBN

Are you using something other than a quick filter for campaign? Like a calculation? 

Would you be able to make a dummy workbook that demonstrates the behavior you are seeing and send it to krose@tableau.com?

Take care,
Keshia

**Comment by eric2003h** [comment]
Hi, 

I am a new user to this extension and the same thing is happening to me.  Has anyone else experienced this?  I have a standard parameter controlling a calculated field that filters a worksheet.  This worksheet is what feeds the data-driven parameter.  Whenever I change the standard parameter's value, the data-driven parameter doesn't change its values until I click on the drop-down.  Only when I click another value in this drop-down does the list update (the values don't update at all once this is published to Tableau Online though, so it is a show stopper until I can figure out a fix).

Any help is appreciated, and thanks in advance!
Eric

**Comment by KeshiaRose** [comment]
Hi @eric2003h,

You are not seeing an update in the extension dropdown because you are changing a native parameter, not a filter. Technically the filter stays the same, for example, if you have a filter for [Category] = [Parameter] the filter always remains on "True", even when you change the parameter value. I have made a simple workaround extension that will trigger the update event for you and therefore automatically update the extension dropdown whenever your native parameter changes. You can find it and instructions on how to use it here: https://glitch.com/edit/#!/param-listener-workaround. I would suggest [remixing](https://glitch.com/help/remix/) it and updating the trex so you have your own version.

Also, the option for "Update list of values on parameter change" is related to the extension itself, not any changes in miscellaneous native parameters in the workbook.

Take care,
Keshia

**Comment by eric2003h** [comment]
@KeshiaRose ,

Absolutely amazing, worked like a charm!  Thank you for this extension and the listener!!!  This gives such great flexibility that was not possible before.

**Comment by mayurdesai24** [comment]
Thank you soo much.. Your code helped me resolve my issue for which i have been working for days.. Appreciate this one
