### ISSUE TITLE
Customers Firewall blocks them from seeing/using the parameters

### ISSUE THREAD

**Issue by JonathanAskild** [tableau/extension-data-driven-parameters#63]
Hey there!
First of all, thanks for a extension which saved us alot of time.
Today we heard from one of our customers that he cant use the parameters at all. And later he found out that their firewall is blocking  the URL: "http://extensions.tableauusercontent.com/sandbox/data-driven-parameters/index.html". They wont let him open it up, because they cant access the URL and cant see its content.
Their exact words: "
Thanks again for your URL re-categorization request. Unfortunately, we are unable to connect to "extensions.tableauusercontent.com/sandbox/data-driven-parameters/index.html" to classify its contents because the site or page has been taken down, or the page contents are not being delivered to us for some other technical reason. Until we can access this site or page, its current categorization will not change."
What to do?

**Comment by JonathanAskild** [comment]
More info from the provider:
![firewall-blocking-parameters](https://user-images.githubusercontent.com/6973856/71671908-99528600-2d74-11ea-8ee3-3058023dc21b.png)

**Comment by KeshiaRose** [comment]
Hi @JonathanAskild,

Sorry for the late reply, I just got back from vacation. Firstly, I noticed the link you had was not on https, that will definitely give you an error when you try to visit that page. However, besides that, even with https, you will see the message: "This version of Tableau does not support sandboxed extensions. Learn More." That is because sandboxed extensions only work within Tableau products where the content security policies that make them sandboxed extensions exist. Their security team will need to use Tableau Desktop or Server/Online to view the actual content of that or any sandboxed extensions. However, we do have documentation on what sandboxed extensions are and how they work, perhaps that will help them classify the URL:

[Manage Dashboard Extensions in Tableau Server](https://help.tableau.com/current/server/en-us/dashboard_extensions_server.htm)

Take care,
Keshia
