### ISSUE TITLE
Feature Request: Enable filter on selection/filter option.

### ISSUE THREAD

**Issue by benblakehart** [tableau/extension-data-driven-parameters#68]
I'll preface by saying I adore this extension. My favorite by a long shot. 

That said, there's behavior in the most recent versions that appears to differ from previous versions. When clicking a mark from the view that contains the list of values for the parameter, the list of available options in the parameter is reduced to only the one I've clicked. This was not previously the case, where selection of a mark in the source view did not affect the dropdown by default. 

Is this intended functionality? I've attached a zip of a workbook with the two different versions of the data driven parameter showing different behavior. To the untrained eye, it looks like v2.1.0 has the "Filter list based on worksheet selections" always turned on, even though that setting was unchecked when testing. 

[DataDrivenParam_issue.zip](https://github.com/tableau/extension-data-driven-parameters/files/4110622/DataDrivenParam_issue.zip)

**Comment by KeshiaRose** [comment]
Wow thanks for the heads up!!! I've decided to remove the option from the configuration for now since it is technically not doing anything and then I'll release a new version later with it in there working. I don't want to mess up people's dashboards where they have been using it and suddenly turn it off. I'll probably add another feature or so into the release too so it will take me a while to get it out. Thank you for letting me know!

**Comment by KeshiaRose** [comment]
Actually I thought about this a little more and there is a way I can fix it without messing up current settings. Look out for a change soon on the same 2.1 version!

**Comment by KeshiaRose** [comment]
Fixed! You'll notice the option is now checked by default if you already had the extension in the dashboard but now when you uncheck the option the updating will stop. Thanks again for putting in the issue!
