### ISSUE TITLE
Selecting multiple values with delimiter not working

### ISSUE THREAD

**Issue by rajmohan006** [tableau/extension-data-driven-parameters#83]
I enabled the below options:
1. Include "(All)" in parameter list.
2. Allow for multiple selections. Delimiter: |
3. Show apply button.

But it only works when i select a single value from the parameter list and if i select more than one value then the dashboard does not show any data.

**Comment by KeshiaRose** [comment]
Hi @rajmohan006, what do you mean it doesn't work? When you select multiple values and click "apply" what do you see in the parameter? It should look something like `Accessories|Appliances|Art`

**Comment by rajmohan006** [comment]
Yes, the parameter looks like "Accessories|Appliances|Art" but the chart goes blank after selecting more than one value.

**Comment by KeshiaRose** [comment]
So the extension is working properly. You need to update your worksheet to accommodate the values in the parameter. For example, if you are trying to filter on the values selected in the parameter, something like `[Sub-Category] = [My Parameter]` is not going to work, because "Accessories" does not equal "Accessories|Appliances|Art" and it will be false. Instead, you will need to do something like `CONTAINS([My Parameter], [Sub-Category])`. This calculation instead will look to see if "Accessories" is **contained in** "Accessories|Appliances|Art" which would return true.
