### ISSUE TITLE
Feature Request: Allow sorting based on different values.

### ISSUE THREAD

**Issue by KeshiaRose** [tableau/extension-data-driven-parameters#9]
For example, sort sub-categories by the sum of sales.

**Comment by MattVoda** [comment]
This would be incredibly useful to me! I'm using this extension for dates, formatted in US style of mm/dd/yyyy, so the default sorting lists all Decembers for every year, then all Novembers, etc.

**Comment by KeshiaRose** [comment]
HI @MattVoda, 

It actually sounds like you just want different formatting for dates. I've added this feature to the second version of the extension, download the new trex and try it out!

https://extensiongallery.tableau.com/products/27

Take care,
Keshia

**Comment by MattVoda** [comment]
I'm on v2.0. It's not the formatting of the dates, but their sort order.
If I sort them in the linked worksheet, that sorting does not carry over to their order in the drop down.
I'd like the ability to reflect worksheet sorting, or to have similar sort control as on worksheets - like to sort based on values in another field.

**Comment by KeshiaRose** [comment]
Oh interesting, so you are sorting the dates in a different way than chronologically? Can you tell me more about your use case? I am still planning on building this feature in the future so would be helpful to have some test cases.

Take care,
Keshia

**Comment by MattVoda** [comment]
I'm using the extension to populate a parameter list of dates. There is a 'most recent' string value, and then every past month-end date for the last 5 years. Technically all strings, to accommodate the text 'most recent'. Each month, a new month-end date is added to the list (via a stored procedure populating the linked worksheet).
I'd like to sort them in reverse chronological order ('most recent' followed by the latest month-end, then the month before that, etc). Since they're strings, I can only sort alphabetically A-Z or Z-A. This sorts the date strings by their first number value, in this case the month in US format, so first you get 'most recent', then all the Decembers (12) for the past 5 years, then all the Novembers (11), etc.
I have a 'sort order' field on the worksheet that can order them how I'd like. Would be great to sort on this field.
But I'm realizing my mix of string and dates (making them all strings) is probably the main issue I could fix now. But I do like the UX of reassuring the user that they're in 'most recent' mode without them having to compare dates.

**Comment by KeshiaRose** [comment]
Ahhh I see, that makes more sense now, yes the addition of the "most recent" option forces you to use strings which is where the problem came from. I'm not sure when I will have time to add this feature but in the meantime, you might be able to get away with using numbers instead as a workaround. Instead of using a string field you could have one field that has the numerical representation of the date (*ex: 20180531) and use a random large number as the placeholder for "most recent" (ex: 10000000). Then you could use a formatted field as the display values so they show up as text (ex: May 2019) but the underlying data is the numbers and therefore is sorted properly. Just a thought, thank you for the use case, I'll use it when I test out scenarios for this feature! 😄 

Take care,
Keshia

**Comment by MattVoda** [comment]
Sounds like a promising approach! I'll try it out next week and check back with how it works. 

Thanks for the responsiveness and help Keshia :)

**Comment by MattVoda** [comment]
Hey, your method works great. Thanks!

**Comment by mlaflash** [comment]
Just to throw in another use-case for this enhancement -- we would like to select a parameter value of a username (which is used to filter our data to just that selected individual) but present it in alphabetical order Last, First.  

Currently, it basically ends up sorted by first initial because of how the usernames are created, making it difficult to locate the individual that you want to choose.
